### PR TITLE
fetchPipMetadata: fixes

### PR DESCRIPTION
**Pull request by fufexan**
- ~~fetchPipMetadata: avoid deprecation warning~~
- fetchPipMetadata: compute hash for non-FOD paths

### CODE REVIEW

**Review by phaer — CHANGES_REQUESTED** [review]
Fod changes look good thanks. 

But the show-derivation "change breaks for nix <2.15 which we still want to support, given thats true for nix stable.

**Comment by fufexan** [comment]
Oh, good point. I'll remove that change then.

**Review by phaer — APPROVED** [review]

**Comment by phaer** [comment]
Are, we still need to integrate the merge queue and hercules-ci somehow, it seems. PRs from external forks still don't trigger ci builds yet. cc @DavHau who could overrule this and has full perms.

**Comment by DavHau** [comment]
Thinking about this, I notice that we should probably better not lock URL's and hashes of store paths at all, because their presence in the store indicates that the URL and hash are already defined somewhere else and we don't want to have a second source of truth.

I remember, I was running into this problem with the dream-lock.json format where whenever there was a store path in the lock we intentionally filtered it out when parsing the lock, to not run into some weird problems.

**Comment by DavHau** [comment]
Anyways, as it fixes a bug currently, I'll merge it.

**Comment by DavHau** [comment]
> PRs from external forks still don't trigger ci builds yet

Is that only for first time contributors or every external fork?

**Comment by phaer** [comment]
> Thinking about this, I notice that we should probably better not lock URL's and hashes of store paths at all, because their presence in the store indicates that the URL and hash are already defined somewhere else and we don't want to have a second source of truth.

Yes, that's a good point. @fufexan what was your use case here?

> Anyways, as it fixes a bug currently, I'll merge it.

Don't see how, tbh? This looks like a new "feature" insofar as that it would correctly error out without this change, no?

> Is that only for first time contributors or every external fork?

Afaiu its coupled to write permissions to this repo for security reasons, so whether it's a first-time contributions or not should not make a difference?

**Comment by fufexan** [comment]
@phaer without this change, using a flake input as the `src` for `mkDerivation` errors out. @DavHau instructed me to make this change in the Matrix room.

**Comment by DavHau** [comment]
see https://matrix.to/#/!PrIEtcffTLLzUWvJOS:matrix.org/$9Rv9hoW0fIdNa7p3jBK8DdbEJsrFRBiWcgh-WvYYnfM?via=nixos.org&via=matrix.org&via=nixos.dev

**Pull request merged**
