### PR TITLE
nodejs: fix symlink issues

### LINKED ISSUE #471: strict-builder for nodejs fails on package; 'File exists' when _create_package_from_derivation tries to create symlinks
The package 'react-native-unimodules' builds successfully with the granular builder, but fails on the strict builder. Here's a minimal reproduction of the issue https://github.com/irisjae/dream2nix-test-case

Nix logs gives us the following stack trace:
```
Traceback (most recent call last):
  File "/nix/store/2q2h7x71jzj3kcddkpcqkn62q39f6fgz-builder/bin/.d2nNodeModules-wrapped", line 9, in <module>
    sys.exit(d2nNodeModules())
  File "/nix/store/2q2h7x71jzj3kcddkpcqkn62q39f6fgz-builder/lib/python3.10/site-packages/app/main.py", line 34, in d2nNodeModules
    create_node_modules()
  File "/nix/store/2q2h7x71jzj3kcddkpcqkn62q39f6fgz-builder/lib/python3.10/site-packages/app/lib/node_modules.py", line 133, in create_node_modules
    _make_folders_rec(
  File "/nix/store/2q2h7x71jzj3kcddkpcqkn62q39f6fgz-builder/lib/python3.10/site-packages/app/lib/node_modules.py", line 105, in _make_folders_rec
    _create_package_from_derivation(
  File "/nix/store/2q2h7x71jzj3kcddkpcqkn62q39f6fgz-builder/lib/python3.10/site-packages/app/lib/node_modules.py", line 54, in _create_package_from_derivation
    (target / Path(entry)).symlink_to(dep.derivation / Path(entry))
  File "/nix/store/hp8vf91s8z2gljwdrf0i4jry8m3899m7-python3-3.10.7/lib/python3.10/pathlib.py", line 1255, in symlink_to
    self._accessor.symlink(target, self, target_is_directory)
FileExistsError: [Errno 17] File exists: '/nix/store/2gliinpkw8mjwlmjv5vnqxxp2yvr0vll-__at__babel__slash__core-7.9.0-lib/node_modules' -> '/nix/store/5k03wg3dlawpng2r5c4pg290pmhddarv-node-modules/@babel/core/node_modules'
```

I'm not sure why such a scenario of symlinking to a path that already exists is possible from a brief look at the Python builder script.

### PR DESCRIPTION
**Pull request by hsjobeki**
Fixes #471 

Resolves edge-cases where the "package.json" file is not created yet in the directory but its nested node_modules are already created. Thus it creates a conflict, when trying to install the node_modules again.

Emits an Info into the logs just in case we need to further inspect this in the future.

@irisjae can you test if that works for your test case. Your project didnt provide any examples i could test other than building all dependencies.

### CODE REVIEW

**Comment by irisjae** [comment]
Thanks, let me try it

**Comment by irisjae** [comment]
@hsjobeki Unfortunately, it seems that we probably need to figure out the root cause of the problem.

Your patch fixes the case with installing the single module 'react-native-unimodules', but adding another module 'react-dev-utils' breaks it. It appears that the problem is related to the presence of different versions of 'escape-string-regexp' from 'react-native-unimodules' and 'react-dev-utils'. Conversely, building 'react-native-unimodules' with other modules that don't contain common dependencies or the same versions of common dependencies appear to succeed. Perhaps this is related to something in the dependency resolution in the strict builder.

Nix logs as follows:
```
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking sources
unpacking source archive /nix/store/rksrjx4qk9fwvwr33v0g54zj65x3ny22-react-native-unimodules-0.13.3.tgz-extracted
@nix { "action": "setPhase", "phase": "patchPhase" }
patching sources
@nix { "action": "setPhase", "phase": "skipForeignPlatform" }
skipForeignPlatform
@nix { "action": "setPhase", "phase": "configurePhase" }
configuring
@nix { "action": "setPhase", "phase": "installPhase" }
installing

> react-native-unimodules@0.13.3 postinstall /private/tmp/nix-build-react-native-unimodules-0.13.3.drv-0/react-native-unimodules-0.13.3
> node ./scripts/postinstall.js

internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'escape-string-regexp'
Require stack:
- /nix/store/9561amq7m6f1wl4w58xzhbqczyd7388p-chalk-2.4.2-lib/index.js
- /private/tmp/nix-build-react-native-unimodules-0.13.3.drv-0/react-native-unimodules-0.13.3/scripts/postinstall.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/nix/store/9561amq7m6f1wl4w58xzhbqczyd7388p-chalk-2.4.2-lib/index.js:2:28)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/nix/store/9561amq7m6f1wl4w58xzhbqczyd7388p-chalk-2.4.2-lib/index.js',
    '/private/tmp/nix-build-react-native-unimodules-0.13.3.drv-0/react-native-unimodules-0.13.3/scripts/postinstall.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-native-unimodules@0.13.3 postinstall: `node ./scripts/postinstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-native-unimodules@0.13.3 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

Extended test case: https://github.com/irisjae/dream2nix-test-case/tree/8b1569ffa6abd7f082a6ad09c70ea8f6f5f0d650

**Comment by hsjobeki** [comment]
can you run "ls -la /nix/store/9561amq7m6f1wl4w58xzhbqczyd7388p-chalk-2.4.2-lib/node_modules"

**Comment by hsjobeki** [comment]
Ok. Seems this is an issue with pre and post-install scripts (again). I'll need some time to dig into the problems there. 
I think we can merge this PR already because it fixes the symlink issue. @DavHau ?

**Comment by irisjae** [comment]
@hsjobeki Yes, it does. I agree that this issue can be considered closed for now. I looked into it and I think the script in question is basically irrelevant noise code that prints some kind of success message. I'm currently looking into the dream2nix override system and how to skip the npm post-install for this particular package.

**Comment by hsjobeki** [comment]
If you want to disable the scripts this is not yet documented and has no flags that are dedicated to do that.

I can provide the following override that is a little hacky but does the job

```nix
#...
outputs =
	{ self, nixpkgs, dream2nix }:
		dream2nix .lib .makeFlakeOutputs {
			systems = [ "x86_64-darwin" "x86_64-linux"];
			config .projectRoot = ./.;
			source = ./.;
			projects = ./projects.toml;
			packageOverrides = {
				"react-native-unimodules" = {
						"disableScripts" = {
							preInstall = ''
								export isMain=true
							'';
							postInstall = ''
								export isMain=false
							'';
						};
					};
			};
		};
}
```

**Pull request merged**
