### PR TITLE
rust: add support for workspace-inherited crate versions

### PR DESCRIPTION
**Pull request by 71**
Adds support for [`workspace.package.version`](https://doc.rust-lang.org/cargo/reference/workspaces.html#the-package-table) in the root `Cargo.toml` and `package.version.workspace = true` in child `Cargo.toml` files.

Not sure how much we're expected to test things. A lot of things are breaking on my Nix setup (I'm running in codespaces which don't really support Nix), so I wasn't able to test everything. Nonetheless, the following worked:

```sh
$ nix flake show $(realpath .)/examples/rust_workspace-version-inheritance --override-input dream2nix $(realpath .)
...
├───apps
│   └───x86_64-linux
│       └───detect-projects: app
├───devShells
│   └───x86_64-linux
│       ├───app: development environment 'devshell'
│       └───default: development environment 'devshell'
└───packages
    └───x86_64-linux
        ├───app: package 'app-0.1.0'
        ├───default: package 'app-0.1.0'
        └───resolveImpure: package 'resolve'

$ nix run $(realpath .)/examples/rust_workspace-version-inheritance --override-input dream2nix $(realpath .)
...
hello from v0.1.0

$ nix run '.#detect-projects' $(realpath .)/examples/rust_workspace-version-inheritance
# projects.toml file describing inputs for dream2nix
#
# To re-generate this file, run:
#   nix run .#detect-projects $source
# ... where `$source` points to the source of your project.
#
# If the local flake is unavailable, alternatively execute the app from the
# upstream dream2nix flake:
#   nix run github:nix-community/dream2nix#detect-projects $source

[""]
name = ""
relPath = ""
subsystem = "rust"
translator = "cargo-lock"
translators = [ "cargo-lock", "cargo-toml",]

["".subsystemInfo]
workspaceMembers = [ "app",]
[["".subsystemInfo.crates]]
name = "app"
relPath = "app"
version = "0.1.0"
``` 

AFAIK the name of the workspace being empty happens regardless of my PR.

### CODE REVIEW

**Comment by woile** [comment]
This almost worked for me, I had an error with `license`: https://github.com/nix-community/dream2nix/blob/main/src/subsystems/rust/builders/utils.nix#L58

I wonder if it works with all the [valid keys for workspace.package](https://doc.rust-lang.org/cargo/reference/workspaces.html#the-package-table)

I solved it by hardcoding the dependencies in the sub-crates directly for now.

**Comment by 71** [comment]
Ah, my change only works for `version` because it made `dream2nix` completely unusable on my workspace as it couldn't find the version of each package. It can probably be changed to work with more fields, though.

**Comment by phaer** [comment]
@71 This seems to break the test suite?

**Comment by DavHau** [comment]
Looks good. Please revert all the lock file updates from `v1/nix/modules/drvs`. Then it should be good to merge.

**Comment by DavHau** [comment]
[this commit](https://github.com/nix-community/dream2nix/pull/525/commits/5f0a5f01b56df277c4e43133bc5f991bd17647a1) still touches the lock files. Mind removing it? Thanks.

**Comment by 71** [comment]
I wasn't sure how locks work since I got errors last time. I removed all files in `v1`, rebased, and squashed my changes. Hopefully that does it.

**Pull request merged**
