### PR TITLE
Fix nodejs naming

### PR DESCRIPTION
**Pull request by xyven1**
This is a fix for #553

### CODE REVIEW

**Comment by DavHau** [comment]
This only seems to work for newer nodejs versions and fails for older ones.

**Comment by xyven1** [comment]
Any clue why that is? If I go to nixpkg search I can see node versions node_(14|16|18|20), so I assumed all of those versions would work

**Comment by DavHau** [comment]
Did you check the exact nixpkgs version pinned by dream2nix?

**Comment by xyven1** [comment]
Nope, guess I shoulda done that

**Pull request closed without merging**
