### PR TITLE
groups: change structure

### PR DESCRIPTION
**Pull request by DavHau**
renames:
- packages.foo."1.0.0" -> packages.foo."1.0.0".conf
- packagesEval.foo."1.0.0" -> packages.foo."1.0.0".evaluated
- public.packages.foo."1.0.0" -> packages.foo."1.0.0".public

### CODE REVIEW

**Comment by FRidh** [comment]
Any reason to use `conf` instead of say `config` which is also used in NixOS? Or is it because they're not exactly the same?

**Comment by DavHau** [comment]
They are not exactly the same. `conf` is a module which itself can have `config` and `options`. We could name it `module` instead but I thought `conf` is better.

Or would it be better to rename `conf` to `module`?

**Comment by FRidh** [comment]
Yes, module is more clear I think. Regardless, being explicit like this about the different attributes is very helpful.

**Comment by DavHau** [comment]
done in https://github.com/nix-community/dream2nix/pull/761

**Pull request merged**
