### PR TITLE
WIP: Port rust subsystem to using drv-parts

### PR DESCRIPTION
**Pull request by DavHau**
@yusdacra I currently don't have much time to proceed with this. If you could take it on from here, it would be great.

- ripgrep already builds.
- I backported https://github.com/nix-community/dream2nix/pull/525 and created an example, but the build currently fails. Maybe it's just because a different builder is used, but I'm not sure.

### CODE REVIEW

**Comment by yusdacra** [comment]
I ported the crane builder since it's the more complete and better working one, builds both of the rust examples right now. Still have to look at why buildRustPackage fails at building that one example but I think I can take a look at it later. Is there anything else specifically you want me to do? I still have to add the devshell back, and probably some options to the crane builder to make doing some stuff easier (mainly setting cargo flags and whatnot).

**Comment by yusdacra** [comment]
added a few options for setting flags and profiles, and disabling tests

**Comment by yusdacra** [comment]
i added two new options for configuring the main derivation and the dependencies derivation, i wanted to use the `mkDerivation` module for those options but i couldnt get it to work properly so just went with a module with a freeform type declared for now.

**Comment by DavHau** [comment]
I pushed some changes to make the crane module use mkDerivation for the top level and dependency derivation. Does this look alright to you?

**Comment by yusdacra** [comment]
> I pushed some changes to make the crane module use mkDerivation for the top level and dependency derivation. Does this look alright to you?

Yes, thats what I've wanted to do aswell. I'll test it soon and see if it's working as intended.

**Pull request merged**
