### PR TITLE
init: php v1

### PR DESCRIPTION
**Pull request by aszenz**
Relates to #550

### CODE REVIEW

**Comment by DavHau** [comment]
Hey @aszenz how are things with that P?. By now we have removed the `./src` directory. Would you mind rebasing your work?

**Comment by aszenz** [comment]
> Hey @aszenz how are things with that PR? By now we have removed the `./src` directory. Would you mind rebasing your work?

Rebased now, I can't seem to get a start on the granular module it's hard to know what each module should accept/return. For now i copied the old module from legacy

**Comment by DavHau** [comment]
merged via https://github.com/nix-community/dream2nix/pull/623

**Comment by DavHau** [comment]
Thanks for your work @aszenz

**Pull request closed without merging**
